import type { LanguagePack } from "./types.js";

export const dePack: LanguagePack = {
  language: "de",
  roleKeywords: [
    "unterassistenz",
    "unterassistent",
    "unterassistentin",
    "wahlstudienjahr",
    "praktisches jahr",
    "pj",
    "famulatur",
    "medizinstudierende",
  ],
  applicationKeywords: ["bewerbung", "bewerbungen", "bewerben", "kontakt", "online-formular"],
  availabilityKeywords: ["ab sofort", "freie platze", "freie plätze", "verfugbar", "verfügbar"],
  unavailableKeywords: ["ausgebucht", "keine freien platze", "keine freien plätze"],
  monthNames: {
    januar: "01",
    februar: "02",
    marz: "03",
    maerz: "03",
    märz: "03",
    april: "04",
    mai: "05",
    juni: "06",
    juli: "07",
    august: "08",
    september: "09",
    oktober: "10",
    november: "11",
    dezember: "12",
  },
  durationPatterns: [/\b\d{1,2}\s*(?:bis|-|–)\s*\d{1,2}\s*(?:wochen|monate)\b/i],
  leadTimePatterns: [/\b(?:bewerbungen?\s+)?\d{1,2}\s+monate?\s+im\s+voraus\b/i],
  departmentAliases: [
    { normalized: "internal-medicine", names: ["Innere Medizin"] },
    { normalized: "surgery", names: ["Chirurgie"] },
    { normalized: "pediatrics", names: ["Pädiatrie", "Padiatrie", "Kinderklinik"] },
    { normalized: "gynecology", names: ["Gynäkologie", "Gynaekologie", "Frauenheilkunde"] },
    { normalized: "psychiatry", names: ["Psychiatrie"] },
    { normalized: "anesthesiology", names: ["Anästhesie", "Anästhesiologie", "Anaesthesie"] },
    { normalized: "emergency-medicine", names: ["Notfallmedizin", "Notfallstation"] },
    { normalized: "radiology", names: ["Radiologie"] },
    { normalized: "neuroradiology", names: ["Neuroradiologie"] },
    { normalized: "ophthalmology", names: ["Augenheilkunde", "Augenklinik"] },
    { normalized: "orthopedics", names: ["Orthopädie", "Orthopadie", "Traumatologie"] },
  ],
};
