import type { LanguagePack } from "./types.js";

export const frPack: LanguagePack = {
  language: "fr",
  roleKeywords: [
    "stage",
    "stagiaire",
    "sous-assistant",
    "sous-assistante",
    "etudiant en medecine",
    "étudiant en médecine",
  ],
  applicationKeywords: ["candidature", "postulation", "contact", "formulaire"],
  availabilityKeywords: ["des maintenant", "dès maintenant", "disponible", "places disponibles"],
  unavailableKeywords: ["complet", "aucune place disponible"],
  monthNames: {
    janvier: "01",
    fevrier: "02",
    février: "02",
    mars: "03",
    avril: "04",
    mai: "05",
    juin: "06",
    juillet: "07",
    aout: "08",
    août: "08",
    septembre: "09",
    octobre: "10",
    novembre: "11",
    decembre: "12",
    décembre: "12",
  },
  durationPatterns: [/\b\d{1,2}\s*(?:a|-|–)\s*\d{1,2}\s*(?:semaines|mois)\b/i],
  leadTimePatterns: [/\bcandidature\s+\d{1,2}\s+mois\s+(?:a\s+l'avance|à\s+l'avance|avant)\b/i],
  departmentAliases: [
    { normalized: "internal-medicine", names: ["Médecine interne", "Medecine interne"] },
    { normalized: "surgery", names: ["Chirurgie"] },
    { normalized: "pediatrics", names: ["Pédiatrie", "Pediatrie"] },
    { normalized: "gynecology", names: ["Gynécologie", "Gynecologie"] },
    { normalized: "psychiatry", names: ["Psychiatrie"] },
    { normalized: "anesthesiology", names: ["Anesthésiologie", "Anesthesiologie", "Anesthésie"] },
    { normalized: "emergency-medicine", names: ["Urgences", "Médecine d'urgence"] },
    { normalized: "radiology", names: ["Radiologie"] },
    { normalized: "neuroradiology", names: ["Neuroradiologie", "Neuroradiologie"] },
    { normalized: "ophthalmology", names: ["Ophtalmologie"] },
    { normalized: "orthopedics", names: ["Orthopédie", "Orthopedie", "Traumatologie"] },
  ],
};
